grpc.server.host=127.0.0.1

grpc.accueil.port=50051
grpc.hospitalisation.port=50052
grpc.paiement.port=50053
grpc.consultation.port=50054
grpc.laboratoire.port=50055
grpc.pharmacie.port=50056
grpc.maternite.port=50057

grpc.deadline.seconds=10
app.title=Hospital Management System
app.version=1.0.0